DROP TABLE IF EXISTS Feeding;
DROP TABLE IF EXISTS Feeding_Schedule;
DROP TABLE IF EXISTS Medical_History;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Animal;
DROP TABLE IF EXISTS Species;
DROP TABLE IF EXISTS Farm;
DROP TABLE IF EXISTS Users;
